### ISSUE TITLE
Host must be a SignedHeader

### ISSUE THREAD

**Issue by H8to** [NetSPI/AWSSigner#3]
Hey!

I tried using this extension. However, I get the error `{"message":"'Host' must be a 'SignedHeader' in the AWS Authorization."}`

and the request is indeed lacking SignedHeaders information:
`Authorization: AWS4-HMAC-SHA256 Credential=[...]eu-west-1[...], SignedHeaders=, Signature=`

Also AWS Signer throws the following exception for each request:
```
java.lang.UnsupportedOperationException: Request has already been issued
	at burp.e3f.setRequest(Unknown Source)
	at burp.gqz.setRequest(Unknown Source)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:275)
	at burp.dyn.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Can't figure it out though why the header is missing.

**Comment by egru** [comment]
A little late on this one, but were you able to figure it out? I also fixed the error message you were getting. The extension was trying to send the request twice.

**Comment by superuser5** [comment]
thanks for great work!
this is fixed for me by providing signeheaders, example:

GET /?Param1=value1 HTTP/1.1
Host:example.amazonaws.com
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date:20150830T123600Z
Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20190101/us-west-1/test/request, **SignedHeaders=content-type;host;x-amz-date,** Signature=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
