### ISSUE TITLE
Doesn't work at java 11 and Burp v2.0.18

### ISSUE THREAD

**Issue by ttffdd** [NetSPI/AWSSigner#6]
Stacktrace is
```
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at burp.Utility.signRequest(Utility.java:104)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:268)
	at burp.dh0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at burp.Utility.signRequest(Utility.java:104)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:268)
	at burp.dh0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Looks like it doesn't work properly with java version more than 8 as said at
[stackoverflow](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j)

P.S. I don't know java well

**Comment by egru** [comment]
Thanks for letting me know. I updated the build config so it should work for all Java versions now. You can grab the new build in the releases or build it yourself with gradle.
